### ISSUE TITLE
Need hook into delay after clicking "Allow" and onCurrentUserChanged firing

### ISSUE THREAD

**Issue by drewwarren** [flutter/google_sign_in#10]
Currently after clicking allow the previous UI is displayed for ~1 second before onCurrentUserChanged fires. This makes the user questions if "Allow" even worked during that 1 second and is undesired. I would love to be able to display a loading indicator during this time.

I can't simply switch to a loading indicator when calling signIn because if the user clicks deny I have no way of hooking into "Deny" to switch away from said loading indicator.

**Comment by collinjackson** [comment]
I am working on supporting this for the next iteration of the API. Thanks!

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter#5323
