### ISSUE TITLE
Need hook into when signInSilently completes

### ISSUE THREAD

**Issue by drewwarren** [flutter/google_sign_in#12]
Currently our "Sign in" page is displayed for ~1 second before signInSilently succeeds. I'd love to show a loading indicator during this time but I don't see a way to hook into this. I only want to show the sign in page if signInSilently cannot sign the user in.

**Comment by collinjackson** [comment]
I am working on supporting this for the next iteration of the API. Thanks!

**Comment by eseidelGoogle** [comment]
Drew asked about this and https://github.com/flutter/google_sign_in/issues/10 today in our meeting.  Presumably this is part of the HostMessages update you have in progress?

**Comment by collinjackson** [comment]
Yes, this is fixed in the v2 branch.

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter#5322
