### ISSUE TITLE
Add google_sign_in package to pub

### ISSUE THREAD

**Issue by drewwarren** [flutter/google_sign_in#13]
Currently I have to specify a path to google_sign_in in `pubspec.yaml`. This is not ideal.

**Comment by collinjackson** [comment]
You can also use a git reference, e.g.
dependencies:
  kittens:
    git: git://github.com/flutter/google_sign_in.git

I think we should be able to do a pub package once I finish removing binaries from the repository.

**Comment by drewwarren** [comment]
I did not know about this. This is all I need. Thanks!
